runtime: python27
api_version: 1
threadsafe: true
instance_class: F4_1G

handlers:
# - url: /.*
#   script: main.app

- url: /
  static_files: index.html
  upload: index\.html
  secure: always

- url: /off-canvas_files
  static_dir: css